Repository Helixis/Shiptest, pull requests merged in 2023-08, with the labels that each got.

#9 SSV Andromeda
  _maps/HISPANIAconfigs/syndicate_andromeda.json
  _maps/shuttles/shiptestHISPANIA/syndicate_andromeda.dmm
Labels: Nave Hispanica

#16 Andromeda arreglos
  _maps/shuttles/shiptestHISPANIA/syndicate_andromeda.dmm
Labels: Nave Hispanica, Fix

#13 Hammer-Class Mercenary Ship
  _maps/HISPANIAconfigs/independent_hammer.json
  _maps/shuttles/shiptestHISPANIA/independent_hammer.dmm
  code/hispania/modules/jobs/job_types/hammer.dm
  code/hispania/modules/recycling/disposal/bin.dm
  icons/hispania/obj/atmospherics/pipes/disposal.dmi
  shiptest.dme
Labels: Nave Hispanica

#18 Artillery 1: Interdiction HARBLUN
  code/datums/mapgen/planetary/WasteGenerator.dm
  code/game/objects/effects/spawners/lootdrop.dm
  code/hispania/game/objects/items/circuitboards/computer_circuitboards.dm
  code/hispania/game/objects/items/circuitboards/machine_circuitboards.dm
  code/hispania/game/objects/structures/salvaging.dm
  code/hispania/modules/overmap/ships/controlled_ship_datum.dm
  code/hispania/modules/research/designs/artillery_designs.dm
  code/hispania/modules/shipscombat/interdiction.dm
  code/hispania/modules/shipscombat/interdiction_machine.dm
  code/modules/overmap/helm.dm
  code/modules/overmap/ships/controlled_ship_datum.dm
  code/modules/research/techweb/all_nodes.dm
  icons/hispania/obj/machines/artillery.dmi
  icons/hispania/obj/machines/computer.dmi
  icons/hispania/obj/module.dmi
  icons/hispania/obj/salvage_structure.dmi
  icons/misc/overmap.dmi
  shiptest.dme
  tgui/packages/tgui/interfaces/HelmConsole.js
Labels: Artillery, Feature
